services:
  - type: web
    name: fastapi-render
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -m prisma db push
    startCommand: PYTHONPATH=. uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fastapi-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.11
