from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'User',
    'TodoCategory',
    'Todo',
    'CoinTransaction',
    'Reward',
    'RewardRedemption',
    'Achievement',
    'UserAchievement',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'User': {
        'todos': 'Todo',
        'Todo_categories': 'TodoCategory',
        'coin_transactions': 'CoinTransaction',
        'reward_redemptions': 'RewardRedemption',
        'user_achievements': 'UserAchievement',
    },
    'TodoCategory': {
        'todos': 'Todo',
        'user': 'User',
    },
    'Todo': {
        'user': 'User',
        'category': 'TodoCategory',
        'coin_transactions': 'CoinTransaction',
    },
    'CoinTransaction': {
        'user': 'User',
        'related_todo': 'Todo',
    },
    'Reward': {
        'reward_redemptions': 'RewardRedemption',
    },
    'RewardRedemption': {
        'user': 'User',
        'reward': 'Reward',
    },
    'Achievement': {
        'user_achievements': 'UserAchievement',
    },
    'UserAchievement': {
        'user': 'User',
        'achievement': 'Achievement',
    },
}

# fmt: on